version: "3.9"

services:
  mariadb:
    image: mariadb:10.11
    container_name: photoprism-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: supersecure-root-password
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: strong-db-password
    volumes:
      - /mnt/ssd/photoprism/db:/var/lib/mysql   # database on SSD
    networks:
      - photonet

  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism-app
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "2342:2342"   # access via http://localhost:2342
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "changeme"       # login password
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "strong-db-password"
      PHOTOPRISM_STORAGE_PATH: "/photoprism/storage"
      PHOTOPRISM_ORIGINALS_PATH: "/photoprism/originals"
      PHOTOPRISM_IMPORT_PATH: "/photoprism/import"
    volumes:
      - /mnt/hdd/photos:/photoprism/originals     # family photo library on HDD
      - /mnt/ssd/photoprism/storage:/photoprism/storage  # fast cache & index on SSD
      - /mnt/hdd/import:/photoprism/import        # optional "drop folder" for new photos
    networks:
      - photonet

networks:
  photonet:
    driver: bridge
